name: Update DSA Stats Card

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dsa-stats-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Stats and Save SVG
        run: |
          curl -o dsa-stats.svg https://dsastats.vercel.app/api/codolio/abd


      - name: Force Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dsa-stats.svg
          git commit -m "Update stats card $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force origin HEAD:dsaStats
